/**
 * Static lookup tables for the chat service (ported from chat.py).
 * Ordered structures use arrays of tuples to preserve insertion-order semantics
 * (Python dict iteration order — first match wins).
 */

// ── Home-care advice (English + Hinglish). First substring match wins. ─────
export const MINOR_MEDICINE_MAP: Array<[string, string]> = [
  ["headache", "Rest in a quiet, dark room. Drink plenty of water and apply a cold or warm compress on your forehead. If it persists, please see a doctor."],
  ["fever", "Stay hydrated with water and fluids. Rest well and use a damp cloth on your forehead to cool down. If fever is high or lasts more than 2 days, see a doctor."],
  ["cold", "Drink warm water and herbal teas. Inhale steam to clear nasal congestion. Rest and keep yourself warm."],
  ["cough", "Drink warm water with honey and ginger. Inhale steam. Avoid cold drinks and dusty areas. See a doctor if it lasts more than a week."],
  ["acidity", "Avoid spicy, oily, and fried food. Eat smaller meals. Drink cold water or coconut water. Don't lie down immediately after eating."],
  ["stomach pain", "Rest and avoid spicy or heavy food. Drink warm water. Apply a warm compress on your stomach. See a doctor if pain is severe."],
  ["stomach", "Rest and avoid spicy or heavy food. Drink warm water. Apply a warm compress on your stomach. See a doctor if pain is severe."],
  ["vomiting", "Sip small amounts of water or coconut water frequently. Rest and avoid solid food for a while. See a doctor if it continues."],
  ["nausea", "Sit or lie down in a comfortable position. Sip cold water slowly. Avoid heavy food. Fresh air and ginger tea may help."],
  ["diarrhea", "Drink plenty of water and fluids to avoid dehydration. Avoid dairy and oily food. Eat light food like rice and bananas. See a doctor if it continues."],
  ["loose motion", "Drink plenty of fluids to stay hydrated. Avoid dairy and heavy food. Eat light food. See a doctor if it continues for more than a day."],
  ["itching", "Avoid scratching. Apply a cool, damp cloth on the affected area. Keep skin moisturised. See a doctor if rash spreads."],
  ["skin rash", "Avoid scratching. Apply a cool, damp cloth. Keep skin clean and dry. See a doctor if rash spreads or is painful."],
  ["rash", "Avoid scratching. Apply a cool, damp cloth. Keep skin clean and dry. See a doctor if rash spreads or is painful."],
  ["back pain", "Rest and avoid heavy lifting. Apply a warm compress on the affected area. Gentle stretching may help. See a doctor if pain is severe."],
  ["joint pain", "Rest the joint and avoid putting pressure on it. Apply a warm or cold compress. Gentle movement helps. See a doctor if swelling occurs."],
  ["body pain", "Rest well. Take a warm shower or bath. Stay hydrated. Gentle stretching may help. See a doctor if pain is severe or persistent."],
  ["muscle pain", "Rest and avoid strenuous activity. Apply a warm compress. Gentle stretching helps. See a doctor if it doesn't improve."],
  ["sore throat", "Gargle with warm salt water. Drink warm water, honey, and ginger tea. Avoid cold drinks. See a doctor if swallowing becomes difficult."],
  ["throat pain", "Gargle with warm salt water. Drink warm fluids. Avoid cold drinks and ice cream. See a doctor if it persists."],
  ["eye irritation", "Splash clean, cold water on your eyes. Avoid rubbing. Rest your eyes from screens. See a doctor if irritation persists."],
  ["eye pain", "Close and rest your eyes. Avoid screens. Splash clean water gently. Please see a doctor if pain continues."],
  ["ear pain", "Apply a warm cloth compress on the ear. Do not insert anything into the ear. Rest. Please see a doctor as ear pain needs proper diagnosis."],
  ["tooth pain", "Rinse your mouth with warm salt water. Apply clove (laung) on the painful area for temporary relief. Please see a dentist soon."],
  ["toothache", "Rinse your mouth with warm salt water. Apply clove (laung) for temporary relief. Please see a dentist soon."],
  ["insomnia", "Avoid screens at least 1 hour before bed. Keep your room dark and cool. Try warm milk or chamomile tea before sleeping. See a doctor if it's chronic."],
  ["sleep", "Avoid screens before bed. Maintain a regular sleep schedule. Try warm milk before sleeping. See a doctor if sleeplessness continues."],
  ["anxiety", "Take slow, deep breaths. Go for a short walk. Talk to someone you trust. Avoid caffeine. Please see a doctor if anxiety is affecting your daily life."],
  ["stress", "Take short breaks, go for a walk, and practise deep breathing. Talk to someone. Avoid overworking. See a doctor if stress is persistent."],
  ["weakness", "Rest well and eat nutritious food. Stay hydrated. Get some fresh air. See a doctor if weakness continues for more than a day or two."],
  ["dizziness", "Sit or lie down immediately. Drink water. Avoid sudden movements. See a doctor if dizziness keeps recurring."],
  ["gas", "Avoid carbonated drinks and gas-forming foods. Take a light walk after meals. Drink warm water. Eat smaller meals."],
  ["bloating", "Avoid carbonated drinks and heavy meals. Take a short walk after eating. Drink warm water with a little ginger."],
  ["constipation", "Drink plenty of water. Eat fibre-rich foods like fruits and vegetables. Take a short walk daily. See a doctor if it persists."],
  ["acne", "Wash your face with a gentle cleanser twice daily. Avoid touching your face. Stay hydrated. See a dermatologist for persistent acne."],
  ["pimples", "Keep your face clean. Avoid oily food. Do not pop pimples. Stay hydrated. See a dermatologist if it's severe."],
  ["hair loss", "Eat a balanced diet rich in protein and iron. Avoid tight hairstyles. Manage stress. See a dermatologist for proper diagnosis."],
  ["knee pain", "Rest and avoid stairs or heavy activity. Apply a cold compress if there is swelling. See a doctor if swelling or severe pain occurs."],
  ["leg pain", "Rest with your leg elevated. Apply a warm compress. Gentle stretching may help. See a doctor if pain or swelling is severe."],
  ["swelling", "Elevate the swollen area. Apply a cold compress for injuries. Rest. See a doctor if swelling is severe or accompanied by pain."],
  ["runny nose", "Drink warm water and herbal teas. Inhale steam. Keep yourself warm. See a doctor if it lasts more than a week."],
  ["nose block", "Inhale steam for 5–10 minutes. Drink warm water with tulsi or ginger. Keep your head slightly elevated while sleeping."],
  ["bleeding", "Apply firm pressure on the wound with a clean cloth. Keep it elevated. See a doctor immediately if bleeding is heavy or doesn't stop."],
  ["burn", "Cool the burn under running cold water for at least 10 minutes. Do not apply ice or home remedies. See a doctor for anything beyond a minor burn."],
  ["wound", "Clean the wound gently with clean water. Cover with a clean cloth or bandage. See a doctor if the wound is deep or doesn't stop bleeding."],
  ["cut", "Apply gentle pressure with a clean cloth to stop bleeding. Clean with water. Cover with a bandage. See a doctor if the cut is deep."],
  ["sprain", "Rest the affected area. Apply ice for the first 20 minutes. Keep it elevated. Avoid putting weight on it. See a doctor if pain is severe."],
  ["high bp", "Reduce salt in your diet. Avoid stress. Exercise lightly. Avoid smoking and alcohol. See a doctor to get your BP properly managed."],
  ["low bp", "Lie down with your legs slightly elevated. Drink water. Eat small frequent meals. See a doctor if you feel faint or dizzy."],
  ["sugar", "Avoid sweets and refined carbohydrates. Eat regular small meals. Stay active with light walks. See a diabetologist for proper management."],
  ["periods", "Rest and apply a warm compress on your lower abdomen to ease cramps. Stay hydrated with warm water or herbal teas. Avoid cold drinks and heavy activity. If pain is severe or periods are irregular, please consult a Gynaecologist."],
  ["period pain", "Rest and apply a warm compress on your lower abdomen. Drink warm water or herbal tea. Gentle walking may help. See a doctor if pain is very severe."],
  ["menstrual", "Rest well and use a warm compress on your abdomen. Stay hydrated with warm fluids. Avoid cold drinks. If cramps are severe or bleeding is heavy, please see a Gynaecologist."],
  ["cramps", "Apply a warm compress on the affected area. Rest and stay hydrated with warm fluids. Gentle stretching may help. See a doctor if pain is severe."],
  ["mc", "Rest and apply a warm compress on your lower abdomen. Drink warm water or herbal tea. If pain is severe, consult a Gynaecologist."],
  // Hinglish
  ["bukhar", "Aaram karein aur paani/coconut water zyada piyein. Mathe pe thanda geela kapda rakhein. Agar bukhar 2 din se zyada rahe ya tez ho, doctor se milein."],
  ["tez bukhar", "Thanda geela kapda mathe pe rakhein. Paani peete rahein. Aaram karein. Agar bukhar bahut tez ho toh abhi doctor ke paas jaayein."],
  ["sar dard", "Ek quiet kamre mein aaram karein. Paani piyein aur mathe pe thanda ya garam kapda rakhein. Zyada ho toh doctor se milein."],
  ["sir dard", "Shant jagah pe aaram karein. Paani piyein aur aankhein band karke lete rahe. Zyada ho toh doctor se milein."],
  ["sir mein dard", "Aaram karein, paani piyein. Mathe pe thanda kapda rakhein. Zyada ho toh doctor se milein."],
  ["sar mein dard", "Aaram karein, paani piyein. Mathe pe thanda kapda rakhein. Zyada ho toh doctor se milein."],
  ["khansi", "Garam paani mein shahad aur adrak milake piyein. Steam lein. Thanda paani aur ice cream se bachen. Ek hafte se zyada ho toh doctor se milein."],
  ["khaansi", "Garam paani mein shahad aur adrak milake piyein. Steam lein. Zyada ho toh doctor se milein."],
  ["zukam", "Garam paani piyein. Steam lein. Garam kapde pehnein. Agar zyada ho toh doctor se milein."],
  ["nazla", "Steam lein 5–10 minute. Garam paani tulsi ke saath piyein. Aaram karein."],
  ["naak se paani", "Garam paani piyein. Steam lein. Garam kapde pehnein."],
  ["naak band", "Steam lein. Garam paani tulsi ya adrak ke saath piyein. Sone ke waqt sar thoda utha ke rakhein."],
  ["pet dard", "Aaram karein. Teekha aur bhari cheezein mat khayein. Garam paani piyein. Pet pe garam kapda rakhein. Dard zyada ho toh doctor se milein."],
  ["pet mein dard", "Aaram karein. Halka khana khayein. Garam paani piyein. Dard zyada ho toh doctor se milein."],
  ["pet mein jalan", "Teekha khana avoid karein. Khana khane ke baad seedhe na letein. Naariyal paani piyein. Zyada ho toh doctor se milein."],
  ["pet mein gas", "Halka khana khayein. Khane ke baad thodi walk karein. Garam paani piyein. Carbonated drinks avoid karein."],
  ["ulti", "Thodi thodi der mein paani ya naariyal paani piyein. Solid khana kuch der avoid karein. Zyada ho toh doctor se milein."],
  ["ulti aa rhi", "Aaram se baith jaayein ya letein. Thodi thodi der mein paani piyein. Zyada ho toh doctor se milein."],
  ["ji machlana", "Thodi taaza hawa lein. Thoda thanda paani piyein. Bhaari khana avoid karein. Adrak ki chai help kar sakti hai."],
  ["dast", "Paani aur naariyal paani zyada piyein. Halka khana khayein jaise chawal. Zyada ho toh doctor se milein."],
  ["kabz", "Paani zyada piyein. Fruits aur vegetables khayein. Roz thodi walk karein. Zyada ho toh doctor se milein."],
  ["khujli", "Prabhavit jagah ko mat khujaayein. Thanda geela kapda rakhein. Skin saaf aur dry rakhein. Zyada ho toh doctor se milein."],
  ["kharish", "Prabhavit jagah ko mat khujaayein. Thanda geela kapda rakhein. Zyada ho toh doctor se milein."],
  ["daad", "Prabhavit jagah saaf aur dry rakhein. Mat khujaayein. Doctor se milein diagnosis ke liye."],
  ["kamar dard", "Aaram karein aur bhari cheezein na uthayein. Garam kapda kamar pe rakhein. Halki stretching help kar sakti hai. Zyada ho toh doctor se milein."],
  ["kamar mein dard", "Aaram karein. Garam senkaan karein. Seedha baithein. Zyada ho toh doctor se milein."],
  ["ghutna dard", "Ghutne pe pressure mat daalein. Thanda ya garam senkaan karein. Seedhiyan avoid karein. Sujan ho toh doctor se milein."],
  ["pair mein dard", "Pair utha kar rakhein. Garam senkaan karein. Aaram karein. Zyada ho toh doctor se milein."],
  ["badan dard", "Aaram karein. Garam paani se nhaayein. Halki stretching karein. Paani piyein. Zyada ho toh doctor se milein."],
  ["gala kharaab", "Garam namak ke paani se gargle karein. Garam paani aur shahad piyein. Thanda paani avoid karein. Zyada ho toh doctor se milein."],
  ["gale mein dard", "Garam namak ke paani se gargle karein. Garam paani piyein. Thanda avoid karein."],
  ["gala dukh rha", "Garam namak ke paani se gargle karein. Shahad aur adrak wali chai piyein."],
  ["aankhon mein jalan", "Saaf thande paani se aankhein dhoyein. Mat ragdein. Screens se thodi der ke liye aaram dein. Zyada ho toh doctor se milein."],
  ["aankh mein dard", "Aankhein band karke aaram dein. Saaf paani se dhoyein. Doctor se milein agar dard jari rahe."],
  ["kaan mein dard", "Kaan pe garam kapda rakhein. Kaan mein kuch mat daalein. Doctor se milein — kaan ke dard ki sahi jaanch zaroori hai."],
  ["daant dard", "Garam namak ke paani se kulaa karein. Laung (clove) dard wali jagah pe rakhein — temporary relief milti hai. Jaldi dentist se milein."],
  ["daant mein dard", "Garam namak ke paani se kulaa karein. Laung (clove) rakhein temporary relief ke liye. Dentist se milein."],
  ["chakkar", "Turant baith jaayein ya letein. Paani piyein. Achanak mat uthein. Baar baar ho toh doctor se milein."],
  ["chakkar aa rha", "Baith jaayein ya letein. Paani piyein. Dhire dhire uthein. Zyada ho toh doctor se milein."],
  ["kamzori", "Aaram karein aur poshtik khana khayein. Paani piyein. Zyada ho toh doctor se milein."],
  ["thakaan", "Aaram karein. Paani aur healthy khana lein. Zyada ho toh doctor se milein."],
  ["neend nahi", "Sone se pehle screen band karein. Garam doodh piyein. Kamra thanda aur andhera rakhein. Chronic ho toh doctor se milein."],
  ["ghabrahad", "Gehri saansein lein. Taaza hawa mein jaayein. Kisi bharose waale se baat karein. Zyada ho toh doctor se milein."],
  ["tension", "Thoda aaram karein. Halki kasrat karein. Gehri saansein lein. Kisi se baat karein. Zyada ho toh doctor se milein."],
  ["bp high", "Namak kam khayein. Tension avoid karein. Halki kasrat karein. Cardiologist se milein agar hamesha high rahe."],
  ["sugar zyada", "Meetha avoid karein. Chhoti chhoti meals lein. Halki walk karein. Diabetologist se milein proper management ke liye."],
  ["sujan", "Suji hui jagah upar rakhein. Injury ho toh thanda senkaan karein. Zyada ho toh doctor se milein."],
  ["chot", "Saaf kapde se haemostat karein. Saaf paani se dhoyein. Patti bandh karein. Gehri chot ho toh doctor se milein."],
  ["jal gaya", "10 minute thande behte paani ke neeche rakhein. Ice mat lagayein. Chhoti jalan ke alawa doctor se zaroor milein."],
  // Common transliteration/spacing variants people actually type. The fuzzy
  // phrase matcher in chat.ts catches most drift, but listing the highest-
  // frequency spellings makes them exact matches (faster and always right).
  ["sirdard", "Shant jagah pe aaram karein. Paani piyein aur aankhein band karke lete rahein. Zyada ho toh doctor se milein."],
  ["sardard", "Shant jagah pe aaram karein. Paani piyein. Mathe pe thanda kapda rakhein. Zyada ho toh doctor se milein."],
  ["sar dukh raha", "Aaram karein aur paani piyein. Mathe pe thanda kapda rakhein. Zyada ho toh doctor se milein."],
  ["sar dukh rha", "Aaram karein aur paani piyein. Mathe pe thanda kapda rakhein. Zyada ho toh doctor se milein."],
  ["sir dukh raha", "Aaram karein aur paani piyein. Shant jagah pe lete rahein. Zyada ho toh doctor se milein."],
  ["matha dard", "Aaram karein, paani piyein. Mathe pe thanda kapda rakhein. Zyada ho toh doctor se milein."],
  ["pait dard", "Aaram karein. Teekha aur bhari khana avoid karein. Garam paani piyein. Dard zyada ho toh doctor se milein."],
  ["pait mein dard", "Aaram karein. Halka khana khayein. Garam paani piyein. Dard zyada ho toh doctor se milein."],
  ["pet mai dard", "Aaram karein. Halka khana khayein. Garam paani piyein. Dard zyada ho toh doctor se milein."],
  ["pet me dard", "Aaram karein. Halka khana khayein. Garam paani piyein. Dard zyada ho toh doctor se milein."],
  ["petdard", "Aaram karein. Teekha khana avoid karein. Garam paani piyein. Zyada ho toh doctor se milein."],
  ["pet dukh raha", "Aaram karein. Halka khana khayein. Garam paani piyein. Zyada ho toh doctor se milein."],
  ["bukhaar", "Aaram karein aur paani zyada piyein. Mathe pe thanda geela kapda rakhein. 2 din se zyada rahe toh doctor se milein."],
  ["bukhar", "Aaram karein aur paani zyada piyein. Mathe pe thanda geela kapda rakhein. 2 din se zyada rahe toh doctor se milein."],
  ["bukhar aa raha", "Aaram karein, paani piyein. Thanda geela kapda mathe pe rakhein. Zyada ho toh doctor se milein."],
  ["khansi ho rahi", "Garam paani mein shahad aur adrak milake piyein. Steam lein. Ek hafte se zyada ho toh doctor se milein."],
  ["khaasi", "Garam paani mein shahad aur adrak milake piyein. Steam lein. Zyada ho toh doctor se milein."],
  ["gala kharab", "Garam namak ke paani se gargle karein. Garam paani aur shahad piyein. Thanda avoid karein."],
  ["gale mein kharash", "Garam namak ke paani se gargle karein. Shahad aur adrak wali chai piyein."],
  ["kamar dukh raha", "Aaram karein aur bhari cheezein na uthayein. Garam senkaan karein. Zyada ho toh doctor se milein."],
  ["ghutne mein dard", "Ghutne pe pressure mat daalein. Thanda ya garam senkaan karein. Sujan ho toh doctor se milein."],
  ["daant dukh raha", "Garam namak ke paani se kulaa karein. Laung (clove) rakhein temporary relief ke liye. Dentist se milein."],
  ["aankh dukh rahi", "Aankhein band karke aaram dein. Saaf paani se dhoyein. Doctor se milein agar dard jari rahe."],
  ["kaan dukh raha", "Kaan pe garam kapda rakhein. Kaan mein kuch mat daalein. Doctor se milein."],
  ["ulti ho rahi", "Thodi thodi der mein paani ya naariyal paani piyein. Solid khana avoid karein. Zyada ho toh doctor se milein."],
  ["ji ghabra raha", "Taaza hawa lein. Thanda paani piyein. Bhaari khana avoid karein. Adrak ki chai help kar sakti hai."],
  ["neend nahi aa rahi", "Sone se pehle screen band karein. Garam doodh piyein. Kamra thanda aur andhera rakhein. Chronic ho toh doctor se milein."],
];

export const CITIES: string[] = [
  "delhi", "new delhi", "mumbai", "bangalore", "bengaluru", "hyderabad", "chennai", "kolkata",
  "pune", "ahmedabad", "jaipur", "lucknow", "surat", "kanpur", "nagpur", "indore", "thane",
  "bhopal", "visakhapatnam", "vizag", "pimpri", "patna", "vadodara", "ghaziabad", "ludhiana",
  "agra", "nashik", "faridabad", "meerut", "rajkot", "kalyan", "varanasi", "srinagar",
  "aurangabad", "dhanbad", "amritsar", "allahabad", "prayagraj", "ranchi", "howrah", "coimbatore",
  "jabalpur", "gwalior", "vijayawada", "jodhpur", "madurai", "raipur", "kota", "guwahati",
  "chandigarh", "solapur", "hubballi", "tiruchirappalli", "trichy", "bareilly", "moradabad",
  "mysore", "mysuru", "gurgaon", "gurugram", "aligarh", "jalandhar", "tirupppur", "bhubaneswar",
  "salem", "warangal", "guntur", "bhiwandi", "saharanpur", "gorakhpur", "bikaner", "amravati",
  "noida", "jamshedpur", "bhilai", "cuttack", "firozabad", "kochi", "ernakulam", "thiruvananthapuram",
  "navi mumbai", "dehradun", "kolhapur", "ajmer", "akola", "gulbarga", "jamnagar", "ujjain",
  "loni", "siliguri", "jhansi", "ulhasnagar", "nellore", "jammu", "sangli", "belgaum", "belgavi",
  "mangalore", "mangaluru", "ambattur", "tirunelveli", "malegaon", "gaya", "jalgaon", "udaipur",
  "maheshtala", "davanagere", "kozhikode", "calicut", "kurnool", "rajpur sonarpur", "rajahmundry",
  "bokaro", "south dumdum", "bellary", "patiala", "gopalpur", "agartala", "dhule", "nanded",
  "pondicherry", "puducherry", "shimla", "gangtok", "imphal", "shillong", "aizawl",
  "itanagar", "kohima", "panaji", "goa", "daman", "silvassa", "port blair",
];

// Insertion order matters — longer/specific phrases listed before generic ones.
export const SPECIALITY_KEYWORDS: Array<[string, string]> = [
  ["general physician", "General Physician"], ["general doctor", "General Physician"],
  ["family doctor", "General Physician"], ["family physician", "General Physician"],
  ["primary doctor", "General Physician"], ["regular doctor", "General Physician"],
  ["fever doctor", "General Physician"], ["gp", "General Physician"],
  ["bukhar", "General Physician"], ["khansi", "General Physician"], ["khaansi", "General Physician"],
  ["zukam", "General Physician"], ["nazla", "General Physician"], ["pet dard", "General Physician"],
  ["pet mein dard", "General Physician"], ["pet ki bimari", "General Physician"], ["ulti", "General Physician"],
  ["chakkar", "General Physician"], ["kamzori", "General Physician"], ["thakaan", "General Physician"],
  ["loose motion", "General Physician"], ["dast", "General Physician"],
  ["khana nahi pachta", "General Physician"], ["bhook nahi", "General Physician"],

  ["blood pressure doctor", "Cardiologist"], ["bp doctor", "Cardiologist"],
  ["heart doctor", "Cardiologist"], ["heart specialist", "Cardiologist"], ["heart problem", "Cardiologist"],
  ["chest pain doctor", "Cardiologist"], ["cardiologist", "Cardiologist"], ["cardiac", "Cardiologist"],
  ["cardio", "Cardiologist"], ["heart", "Cardiologist"], ["dil ka doctor", "Cardiologist"],
  ["dil mein dard", "Cardiologist"], ["seene mein dard", "Cardiologist"], ["seena dard", "Cardiologist"],
  ["bp high", "Cardiologist"], ["bp badhna", "Cardiologist"], ["hridya", "Cardiologist"],

  ["doctor for skin", "Dermatologist"], ["skin problem", "Dermatologist"], ["skin issue", "Dermatologist"],
  ["skin disease", "Dermatologist"], ["skin doctor", "Dermatologist"], ["skin specialist", "Dermatologist"],
  ["rash doctor", "Dermatologist"], ["acne doctor", "Dermatologist"], ["pimple doctor", "Dermatologist"],
  ["hair doctor", "Dermatologist"], ["hair loss doctor", "Dermatologist"], ["dermatologist", "Dermatologist"],
  ["derma", "Dermatologist"], ["derm", "Dermatologist"], ["skin", "Dermatologist"], ["acne", "Dermatologist"],
  ["pimple", "Dermatologist"], ["rash", "Dermatologist"], ["eczema", "Dermatologist"], ["psoriasis", "Dermatologist"],
  ["chamdi", "Dermatologist"], ["kharish", "Dermatologist"], ["khujli", "Dermatologist"], ["daad", "Dermatologist"],
  ["balon ka girna", "Dermatologist"], ["baal girna", "Dermatologist"],

  ["doctor for joint", "Orthopedic"], ["doctor for bone", "Orthopedic"], ["joint pain doctor", "Orthopedic"],
  ["knee pain doctor", "Orthopedic"], ["back pain doctor", "Orthopedic"], ["bone doctor", "Orthopedic"],
  ["joint doctor", "Orthopedic"], ["knee doctor", "Orthopedic"], ["spine doctor", "Orthopedic"],
  ["back doctor", "Orthopedic"], ["fracture doctor", "Orthopedic"], ["orthopedic", "Orthopedic"],
  ["orthopaedic", "Orthopedic"], ["ortho", "Orthopedic"], ["bone", "Orthopedic"], ["joint", "Orthopedic"],
  ["haddi", "Orthopedic"], ["ghutna dard", "Orthopedic"], ["kamar dard", "Orthopedic"],
  ["jodon mein dard", "Orthopedic"], ["pair mein dard", "Orthopedic"], ["kamar", "Orthopedic"],

  ["headache doctor", "Neurologist"], ["migraine doctor", "Neurologist"], ["brain doctor", "Neurologist"],
  ["nerve doctor", "Neurologist"], ["nerve specialist", "Neurologist"], ["fits doctor", "Neurologist"],
  ["epilepsy doctor", "Neurologist"], ["neurologist", "Neurologist"], ["neuro", "Neurologist"],
  ["neurology", "Neurologist"], ["brain", "Neurologist"], ["migraine", "Neurologist"], ["seizure", "Neurologist"],
  ["epilepsy", "Neurologist"], ["fits", "Neurologist"], ["sar dard", "Neurologist"], ["sir dard", "Neurologist"],
  ["sar mein dard", "Neurologist"], ["sir mein dard", "Neurologist"], ["sir bhaari", "Neurologist"],
  ["chakkar aana", "Neurologist"], ["mirgi", "Neurologist"],

  ["doctor for child", "Pediatrician"], ["doctor for baby", "Pediatrician"], ["child specialist", "Pediatrician"],
  ["child doctor", "Pediatrician"], ["baby doctor", "Pediatrician"], ["kids doctor", "Pediatrician"],
  ["children doctor", "Pediatrician"], ["infant doctor", "Pediatrician"], ["pediatrician", "Pediatrician"],
  ["paediatrician", "Pediatrician"], ["paeds", "Pediatrician"], ["peds", "Pediatrician"], ["baby", "Pediatrician"],
  ["child", "Pediatrician"], ["bachcha", "Pediatrician"], ["bacha", "Pediatrician"], ["bachche", "Pediatrician"],
  ["bacha bimar", "Pediatrician"], ["bachche ko bukhar", "Pediatrician"], ["nanha", "Pediatrician"],

  ["doctor for women", "Gynecologist"], ["doctor for ladies", "Gynecologist"], ["ladies doctor", "Gynecologist"],
  ["women doctor", "Gynecologist"], ["woman doctor", "Gynecologist"], ["female doctor", "Gynecologist"],
  ["women specialist", "Gynecologist"], ["pregnancy doctor", "Gynecologist"], ["period doctor", "Gynecologist"],
  ["maternity doctor", "Gynecologist"], ["gynecologist", "Gynecologist"], ["gynaecologist", "Gynecologist"],
  ["gynae", "Gynecologist"], ["gyno", "Gynecologist"], ["pregnancy", "Gynecologist"], ["sex doctor", "Gynecologist"],
  ["sex specialist", "Gynecologist"], ["sexual health doctor", "Gynecologist"], ["sexual health", "Gynecologist"],
  ["sexual issue", "Gynecologist"], ["sex issue", "Gynecologist"], ["sex problem", "Gynecologist"],
  ["sex related", "Gynecologist"], ["intimate health", "Gynecologist"], ["std doctor", "Gynecologist"],
  ["sti doctor", "Gynecologist"], ["fertility doctor", "Gynecologist"], ["fertility", "Gynecologist"],
  ["reproductive", "Gynecologist"], ["mahila doctor", "Gynecologist"], ["periods problem", "Gynecologist"],

  ["male sex problem", "Urologist"], ["male sex issue", "Urologist"], ["men sex issue", "Urologist"],
  ["men sex problem", "Urologist"], ["sex problem for men", "Urologist"], ["erectile dysfunction", "Urologist"],
  ["impotence", "Urologist"], ["kidney stone doctor", "Urologist"], ["urinary problem", "Urologist"],
  ["urine problem", "Urologist"], ["burning urine", "Urologist"], ["frequent urination", "Urologist"],
  ["prostate doctor", "Urologist"], ["bladder doctor", "Urologist"], ["kidney doctor", "Urologist"],
  ["urologist", "Urologist"], ["urology", "Urologist"],

  ["doctor for depression", "Psychiatrist"], ["doctor for anxiety", "Psychiatrist"],
  ["mental health doctor", "Psychiatrist"], ["mind doctor", "Psychiatrist"], ["mental doctor", "Psychiatrist"],
  ["depression doctor", "Psychiatrist"], ["anxiety doctor", "Psychiatrist"], ["stress doctor", "Psychiatrist"],
  ["psychiatrist", "Psychiatrist"], ["psychiatry", "Psychiatrist"], ["psych", "Psychiatrist"],
  ["mental", "Psychiatrist"], ["depression", "Psychiatrist"], ["anxiety", "Psychiatrist"], ["stress", "Psychiatrist"],
  ["counselor", "Psychiatrist"], ["therapist", "Psychiatrist"], ["addiction doctor", "Psychiatrist"],
  ["nasha doctor", "Psychiatrist"], ["eating disorder", "Psychiatrist"], ["ocd doctor", "Psychiatrist"],
  ["insomnia", "Psychiatrist"], ["sleep doctor", "Psychiatrist"], ["neend nahi", "Psychiatrist"],
  ["ghabrahad", "Psychiatrist"], ["ghabrana", "Psychiatrist"], ["udaasi", "Psychiatrist"],
  ["tension bahut", "Psychiatrist"], ["man ki takleef", "Psychiatrist"], ["maan ki bimari", "Psychiatrist"],

  ["blood sugar doctor", "Diabetologist"], ["diabetes doctor", "Diabetologist"], ["sugar doctor", "Diabetologist"],
  ["diabetologist", "Diabetologist"], ["diabetes", "Diabetologist"], ["diabetic", "Diabetologist"],
  ["sugar", "Diabetologist"],

  ["ear nose throat", "ENT Specialist"], ["doctor for ear", "ENT Specialist"], ["doctor for throat", "ENT Specialist"],
  ["sinus doctor", "ENT Specialist"], ["tonsil doctor", "ENT Specialist"], ["hearing doctor", "ENT Specialist"],
  ["ent", "ENT Specialist"], ["ear", "ENT Specialist"], ["nose", "ENT Specialist"], ["throat", "ENT Specialist"],
  ["sinus", "ENT Specialist"], ["tonsil", "ENT Specialist"], ["naak band", "ENT Specialist"],
  ["naak se", "ENT Specialist"], ["kaan mein dard", "ENT Specialist"], ["kaan mein", "ENT Specialist"],
  ["gale mein dard", "ENT Specialist"], ["gala kharaab", "ENT Specialist"], ["gala dukh", "ENT Specialist"],

  ["doctor for eye", "Ophthalmologist"], ["eye problem doctor", "Ophthalmologist"], ["eye specialist", "Ophthalmologist"],
  ["eye doctor", "Ophthalmologist"], ["vision doctor", "Ophthalmologist"], ["glasses doctor", "Ophthalmologist"],
  ["specs doctor", "Ophthalmologist"], ["cataract doctor", "Ophthalmologist"], ["ophthalmologist", "Ophthalmologist"],
  ["ophtho", "Ophthalmologist"], ["eye", "Ophthalmologist"], ["vision", "Ophthalmologist"], ["aankh", "Ophthalmologist"],
  ["aankhon mein", "Ophthalmologist"], ["aankhon se", "Ophthalmologist"], ["dhundla dikhna", "Ophthalmologist"],

  ["toothache doctor", "Dentist"], ["teeth doctor", "Dentist"], ["tooth doctor", "Dentist"],
  ["gum doctor", "Dentist"], ["mouth doctor", "Dentist"], ["dentist", "Dentist"], ["dental", "Dentist"],
  ["teeth", "Dentist"], ["tooth", "Dentist"], ["toothache", "Dentist"], ["daant dard", "Dentist"],
  ["daant mein dard", "Dentist"], ["daant", "Dentist"], ["muh mein dard", "Dentist"],
];

export const HOSPITAL_TYPE_KEYWORDS: Array<[string, string]> = [
  ["child", "children"], ["children", "children"], ["paediatric", "children"],
  ["pediatric", "children"], ["kids", "children"], ["baby", "children"],
  ["cardiac", "cardiac"], ["heart", "cardiac"], ["cardio", "cardiac"],
  ["cancer", "cancer"], ["oncology", "cancer"], ["oncologist", "cancer"],
  ["maternity", "maternity"], ["pregnancy", "maternity"], ["delivery", "maternity"],
  ["eye", "eye"], ["ophthalmic", "eye"], ["vision", "eye"],
  ["dental", "dental"], ["teeth", "dental"],
  ["ortho", "orthopedic"], ["bone", "orthopedic"], ["joint", "orthopedic"],
  ["mental", "mental health"], ["psychiatric", "mental health"], ["psychiatry", "mental health"],
  ["trauma", "trauma"], ["emergency", "emergency"],
  ["skin", "dermatology"], ["derma", "dermatology"],
  ["covid", "covid"], ["fever", "fever"],
  ["government", "government"], ["govt", "government"],
  ["private", "private"],
];

export const HOSPITAL_KEYWORDS: string[] = [
  "hospital", "hospitals", "clinic", "clinics", "nursing home",
  "medical centre", "medical center", "medical college", "trauma centre",
  "trauma center", "health centre", "dispensary",
];

export const FAQ_ABOUT_DOCTAR =
  "Doctar is a healthcare platform that helps patients find trusted doctors and healthcare services across India. " +
  "It ranks doctors based on their qualifications, patient reviews, and performance instead of paid promotions. " +
  "Our goal is to make healthcare more transparent, reliable, and accessible for everyone. " +
  "For more info visit doctar.in or call +91-8877772277.";

export const FAQ_KEYWORDS: string[] = [
  "what is doctar", "about doctar", "tell me about doctar", "what does doctar do",
  "doctar kya hai", "ye app kya hai", "yeh app kya hai", "doctar ke baare mein",
  "is app ke baare mein", "what is this app", "doctar platform", "how does doctar work",
  "doctar helpline", "doctar contact", "helpline number", "doctar number",
  "doctar website", "doctar.in", "helpline kya hai", "number batao",
];

// Keep in sync with the `serious_symptom` list in chat.ts's COMBINED_PROMPT —
// Gemini is only consulted for doctor/hospital searches that already name a
// city, so anything the prompt calls an emergency must also be recognised
// here or it falls through to the "I didn't understand that" branch.
export const EMERGENCY_KEYWORDS: Array<[string, string]> = [
  ["cardiac arrest", "cardiac"], ["heart attack", "cardiac"], ["dil ka daura", "cardiac"],
  ["chest pain", "cardiac"], ["seene mein dard", "cardiac"], ["seena dard", "cardiac"],
  ["chhati mein dard", "cardiac"],
  ["stroke", "emergency"], ["paralysis", "emergency"], ["lakwa", "emergency"],
  ["seizure", "emergency"], ["mirgi ka daura", "emergency"], ["not breathing", "emergency"],
  ["can't breathe", "emergency"], ["cant breathe", "emergency"], ["saans nahi aa rahi", "emergency"],
  ["difficulty breathing", "emergency"], ["trouble breathing", "emergency"],
  ["shortness of breath", "emergency"], ["breathlessness", "emergency"],
  ["saans nahi aa rha", "emergency"], ["saans nahi le pa", "emergency"], ["dam ghut raha", "emergency"],
  ["saans phool", "emergency"],
  ["unconscious", "emergency"], ["behosh", "emergency"], ["severe bleeding", "trauma"],
  ["khoon bohot beh", "trauma"], ["bahut khoon beh", "trauma"], ["accident ho gaya", "trauma"],
  ["road accident", "trauma"], ["poisoning", "emergency"], ["zeher kha liya", "emergency"],
  ["overdose", "emergency"], ["severe burn", "trauma"], ["choking", "emergency"],
  ["dum ghut", "emergency"], ["suicide attempt", "emergency"], ["khudkushi", "emergency"],
  // Common home emergencies — previously fell through to "I didn't understand".
  ["nose bleeding", "emergency"], ["nosebleed", "emergency"], ["nose bleed", "emergency"],
  ["bleeding from nose", "emergency"], ["naak se khoon", "emergency"],
  ["fainted", "emergency"], ["fainting", "emergency"], ["passed out", "emergency"],
  ["chakkar aakar gir", "emergency"],
  ["anaphylaxis", "emergency"], ["allergic reaction", "emergency"],
  ["snake bite", "trauma"], ["snakebite", "trauma"], ["saanp ne kaata", "trauma"],
  ["saap ne kaata", "trauma"],
  ["electric shock", "trauma"], ["bijli ka jhatka", "trauma"],
  ["heat stroke", "emergency"], ["heatstroke", "emergency"],
  ["drowning", "emergency"], ["doob gaya", "emergency"],
];

export const EMERGENCY_PAT =
  /\b(cardiac arrest|heart attack|stroke|seizure|fits? (?:aa rahe|aa rha|pad rahe)|not breathing|can'?t breathe|difficulty breathing|trouble breathing|shortness of breath|breathlessness|chest pain|unconscious|severe bleeding|overdose|poisoning|choking|suicide attempt|anaphylaxis|allergic reaction|snake ?bite|nose ?bleed(?:ing)?|bleeding from (?:the )?nose|fainted|fainting|passed out|electric shock|drowning|heat ?stroke)\b|saans (nahi (aa rahi|aa rha|le pa)|phool)|dam ghut|behosh|lakwa|khudkushi|khoon (bohot|bahut) beh|bahut khoon beh|accident ho gaya|zeher kha|seene mein dard|seena dard|chhati mein dard|naak se khoon|saanp ne kaata|saap ne kaata|bijli ka jhatka|doob gaya|chakkar aakar gir/i;

// ── Home first aid ────────────────────────────────────────────────────────
// Deliberately hardcoded, never Gemini-generated: a hallucinated first-aid
// step is the kind of error that injures someone. Steps follow standard
// Red Cross / AHA / NHS guidance, adapted to Indian emergency numbers.
//
// `severity` shapes the reply, not the content:
//   "critical" — life-threatening; the reply leads with "call 108 NOW" and
//                first aid is explicitly framed as what to do while waiting.
//   "urgent"   — usually manageable at home; the reply leads with first aid
//                and states plainly when to escalate. Using the critical
//                framing for a nosebleed would train people to ignore it.
export interface FirstAidGuide {
  label: string;
  severity: "critical" | "urgent";
  steps: string[];
  escalate?: string;
}

export const FIRST_AID_STEPS: Record<string, FirstAidGuide> = {
  heart_attack: {
    label: "Suspected heart attack",
    severity: "critical",
    steps: [
      "Call 108 now. Do not drive the person yourself — ambulance crews can start treatment on the way.",
      "Sit them down, leaning back with knees bent. Loosen tight clothing and keep them calm and still.",
      "If they are conscious, not allergic to aspirin, and not on blood thinners, have them slowly chew one 300 mg aspirin.",
      "Do not give food or water.",
      "If they stop responding and are not breathing normally, start hands-only CPR: push hard and fast in the centre of the chest, about twice per second.",
    ],
  },
  stroke: {
    label: "Suspected stroke",
    severity: "critical",
    steps: [
      "Call 108 now and note the exact time symptoms started — treatment decisions depend on it.",
      "Check F.A.S.T. — Face drooping, Arm weakness, Speech difficulty, Time to call.",
      "Lay them on their side with the head and shoulders slightly raised and supported.",
      "Give nothing by mouth — no food, no water, and no medicine (not even aspirin; not every stroke is a clot).",
      "Stay with them and watch their breathing until help arrives.",
    ],
  },
  choking: {
    label: "Choking",
    severity: "critical",
    steps: [
      "Ask 'Are you choking?' If they can cough forcefully, encourage them to keep coughing and do not intervene.",
      "If they cannot cough, speak or breathe, call 108 and act immediately.",
      "Lean them forward and give up to 5 sharp back blows between the shoulder blades with the heel of your hand.",
      "If that fails, give up to 5 abdominal thrusts: stand behind, place a fist just above the navel, and pull sharply inward and upward.",
      "Alternate 5 back blows and 5 abdominal thrusts. If they become unresponsive, start CPR.",
      "For a baby under 1 year: use back blows and chest thrusts only — never abdominal thrusts.",
    ],
  },
  severe_bleeding: {
    label: "Severe bleeding",
    severity: "critical",
    steps: [
      "Call 108.",
      "Press firmly and directly on the wound with a clean cloth or pad, using the flat of your hand.",
      "Keep pressing without lifting to check. If blood soaks through, add more layers on top.",
      "Raise the injured limb above heart level, unless you suspect a fracture.",
      "If an object is embedded in the wound, do not pull it out — press firmly around it instead.",
      "Lay them down, keep them warm, and watch for pale, clammy skin or confusion (signs of shock).",
    ],
  },
  seizure: {
    label: "Seizure / fits",
    severity: "critical",
    steps: [
      "Stay calm and time the seizure from when it starts.",
      "Move hard or sharp objects out of the way and cushion their head with something soft.",
      "Do NOT restrain them, and do NOT put anything in their mouth — it is impossible to swallow your tongue, and objects cause injury.",
      "Once the convulsions stop, gently roll them onto their side so the airway stays clear.",
      "Call 108 if the seizure lasts over 5 minutes, repeats, is their first ever, or they are injured, pregnant, or do not wake up.",
    ],
  },
  anaphylaxis: {
    label: "Severe allergic reaction",
    severity: "critical",
    steps: [
      "Call 108 immediately — severe allergic reactions can close the airway within minutes.",
      "If they carry an adrenaline auto-injector (EpiPen), help them use it into the outer thigh straight away.",
      "Lay them flat with legs raised. If they are struggling to breathe, let them sit up instead.",
      "Remove the trigger if you can do so safely (for example, a bee sting — scrape it out sideways, don't squeeze).",
      "If breathing stops, start CPR. A second adrenaline dose can be given after 5 minutes if there is no improvement.",
    ],
  },
  snake_bite: {
    label: "Snake bite",
    severity: "critical",
    steps: [
      "Call 108 and get to a hospital with antivenom as fast as possible — this is the only real treatment.",
      "Keep the person still and calm, and keep the bitten limb below heart level. Movement spreads venom faster.",
      "Remove rings, bangles and watches near the bite before swelling starts.",
      "Do NOT cut the wound, suck out venom, apply a tourniquet, or use ice or herbal pastes — all of these cause harm.",
      "If you can do it safely, photograph the snake from a distance. Never try to catch or kill it.",
    ],
  },
  poisoning: {
    label: "Poisoning / overdose",
    severity: "critical",
    steps: [
      "Call 108 immediately and keep the container, packet or strip to show the medical team.",
      "Do NOT make them vomit unless a doctor specifically tells you to — many substances cause more damage coming back up.",
      "If the substance is on the skin or in the eyes, rinse with plenty of clean running water for 15–20 minutes.",
      "If they are unconscious but breathing, roll them onto their side.",
      "If breathing stops, start CPR.",
    ],
  },
  severe_burn: {
    label: "Burn",
    severity: "critical",
    steps: [
      "Stop the burning and move the person away from the source.",
      "Cool the burn under cool (not ice-cold) running water for at least 20 minutes.",
      "Remove rings, watches and tight clothing near the burn before swelling starts — but never peel off anything stuck to the skin.",
      "Cover loosely with cling film or a clean, non-fluffy cloth.",
      "Do NOT apply ice, toothpaste, butter, ghee, haldi, oil or ointments — these trap heat and cause infection.",
    ],
    escalate:
      "Call 108 for burns that are large (bigger than the person's palm), deep, white or charred, or on the face, hands, genitals or airway, and for any burn in a baby or elderly person.",
  },
  nosebleed: {
    label: "Nosebleed",
    severity: "urgent",
    steps: [
      "Sit upright and lean slightly FORWARD — never tilt the head back, as that sends blood down the throat and causes vomiting.",
      "Pinch the soft part of the nose (just below the bony bridge) firmly and continuously for 10 full minutes without releasing to check.",
      "Breathe through the mouth while pinching.",
      "Apply a cold compress or ice pack to the bridge of the nose.",
      "Afterwards, avoid blowing or picking the nose, bending over, and heavy lifting for several hours.",
    ],
    escalate:
      "Go to a hospital if the bleeding doesn't stop after 20 minutes of steady pressure, is very heavy, follows a head injury, or the person is on blood thinners.",
  },
  fainting: {
    label: "Fainting",
    severity: "urgent",
    steps: [
      "Lay the person flat on their back and raise their legs about 30 cm above heart level.",
      "Loosen tight collars, belts and clothing, and make sure they have fresh air.",
      "Most people come round within a minute — keep them lying down for a few more minutes, then let them sit up slowly.",
      "Don't give food or water until they are fully alert.",
    ],
    escalate:
      "Call 108 if they do not wake within 1 minute, are not breathing normally, fainted with chest pain or palpitations, are pregnant, or were injured in the fall.",
  },
  heat_stroke: {
    label: "Heat stroke",
    severity: "critical",
    steps: [
      "Call 108 — heat stroke is life-threatening and body temperature must come down fast.",
      "Move them into shade or an air-conditioned room immediately.",
      "Remove excess clothing and cool them aggressively: cool water over the skin, wet cloths, fanning, ice packs at the neck, armpits and groin.",
      "If they are fully alert, give small sips of cool water or ORS. Never give fluids to someone drowsy or confused.",
      "Keep cooling until help arrives or they feel cool to the touch.",
    ],
  },
  electric_shock: {
    label: "Electric shock",
    severity: "critical",
    steps: [
      "Do NOT touch the person until the current is off — switch off the mains or the fuse first.",
      "If you cannot cut the power, push them away from the source using a dry, non-conducting object such as a wooden stick. Never use anything metal or wet.",
      "Call 108 — electric shock can cause heart rhythm problems that appear later even if they seem fine.",
      "If they are unresponsive and not breathing normally, start CPR.",
      "Cool any burns under running water and cover loosely.",
    ],
  },
};

/**
 * Emergency phrase → first-aid topic. Separate from EMERGENCY_KEYWORDS
 * (which maps to a *hospital* category) because "nosebleed" and "choking"
 * are both hospital-type "emergency" but need completely different steps.
 * Longest/most specific phrases first — first match wins.
 */
export const FIRST_AID_KEYWORDS: Array<[string, string]> = [
  ["cardiac arrest", "heart_attack"], ["heart attack", "heart_attack"],
  ["dil ka daura", "heart_attack"], ["chest pain", "heart_attack"],
  ["seene mein dard", "heart_attack"], ["seena dard", "heart_attack"],
  ["chhati mein dard", "heart_attack"],
  ["stroke", "stroke"], ["paralysis", "stroke"], ["lakwa", "stroke"],
  ["choking", "choking"], ["dum ghut", "choking"], ["dam ghut", "choking"],
  ["severe bleeding", "severe_bleeding"], ["khoon bohot beh", "severe_bleeding"],
  ["bahut khoon beh", "severe_bleeding"],
  ["nose bleeding", "nosebleed"], ["nosebleed", "nosebleed"], ["nose bleed", "nosebleed"],
  ["bleeding from nose", "nosebleed"], ["bleeding from the nose", "nosebleed"],
  ["naak se khoon", "nosebleed"],
  ["seizure", "seizure"], ["mirgi ka daura", "seizure"], ["fits", "seizure"],
  ["anaphylaxis", "anaphylaxis"], ["allergic reaction", "anaphylaxis"],
  ["snake bite", "snake_bite"], ["snakebite", "snake_bite"],
  ["saanp ne kaata", "snake_bite"], ["saap ne kaata", "snake_bite"],
  ["poisoning", "poisoning"], ["overdose", "poisoning"], ["zeher kha", "poisoning"],
  ["severe burn", "severe_burn"], ["burn", "severe_burn"], ["jal gaya", "severe_burn"],
  ["fainted", "fainting"], ["fainting", "fainting"], ["passed out", "fainting"],
  ["behosh", "fainting"], ["chakkar aakar gir", "fainting"],
  ["heat stroke", "heat_stroke"], ["heatstroke", "heat_stroke"],
  ["electric shock", "electric_shock"], ["bijli ka jhatka", "electric_shock"],
];

export const SYMPTOM_HISTORY_MAP: Array<[string, string]> = [
  ["stomach", "General Physician"], ["gastric", "General Physician"], ["abdomen", "General Physician"],
  ["abdominal", "General Physician"], ["digestion", "General Physician"], ["vomit", "General Physician"],
  ["nausea", "General Physician"], ["diarrhea", "General Physician"], ["loose motion", "General Physician"],
  ["fever", "General Physician"], ["cold", "General Physician"], ["cough", "General Physician"],
  ["flu", "General Physician"], ["weakness", "General Physician"],
  ["headache", "Neurologist"], ["migraine", "Neurologist"],
  ["chest", "Cardiologist"], ["heart", "Cardiologist"],
  ["skin", "Dermatologist"], ["rash", "Dermatologist"], ["acne", "Dermatologist"],
  ["joint", "Orthopedic"], ["knee", "Orthopedic"], ["back", "Orthopedic"],
  ["eye", "Ophthalmologist"], ["vision", "Ophthalmologist"],
  ["ear", "ENT Specialist"], ["throat", "ENT Specialist"], ["sinus", "ENT Specialist"],
  ["teeth", "Dentist"], ["tooth", "Dentist"],
  ["sugar", "Diabetologist"], ["diabetes", "Diabetologist"],
  ["mental", "Psychiatrist"], ["anxiety", "Psychiatrist"], ["depression", "Psychiatrist"],
  ["child", "Pediatrician"], ["baby", "Pediatrician"],
  ["period", "Gynecologist"], ["pregnancy", "Gynecologist"],
  ["urine", "Urologist"], ["kidney", "Urologist"],
  ["bukhar", "General Physician"], ["khansi", "General Physician"], ["zukam", "General Physician"],
  ["nazla", "General Physician"], ["pet dard", "General Physician"], ["ulti", "General Physician"],
  ["dast", "General Physician"], ["chakkar", "General Physician"],
  ["sar dard", "Neurologist"], ["sir dard", "Neurologist"],
  ["dil mein", "Cardiologist"], ["seena", "Cardiologist"],
  ["chamdi", "Dermatologist"], ["kharish", "Dermatologist"], ["khujli", "Dermatologist"],
  ["ghutna", "Orthopedic"], ["kamar", "Orthopedic"], ["haddi", "Orthopedic"],
  ["aankh", "Ophthalmologist"], ["aankhon", "Ophthalmologist"],
  ["kaan", "ENT Specialist"], ["naak", "ENT Specialist"], ["gala", "ENT Specialist"],
  ["daant", "Dentist"], ["bachcha", "Pediatrician"], ["bacha", "Pediatrician"],
  ["neend", "Psychiatrist"], ["ghabrahad", "Psychiatrist"],
  ["peshab", "Urologist"], ["pathri", "Urologist"],
];

const SYMPTOM_TO_SPECIALTY: Array<[string, string]> = [
  ["irregular cycle", "Gynecologist"], ["period pain", "Gynecologist"], ["periods problem", "Gynecologist"],
  ["fever in child", "Pediatrician"], ["menstruation", "Gynecologist"], ["menstrual", "Gynecologist"],
  ["garbhavati", "Gynecologist"], ["cramps", "Gynecologist"], ["periods", "Gynecologist"],
  ["period", "Gynecologist"], ["mc", "Gynecologist"], ["mahila", "Gynecologist"], ["pregnancy", "Gynecologist"],
  ["chest pain", "Cardiologist"], ["blood pressure", "Cardiologist"], ["palpitation", "Cardiologist"],
  ["seene mein", "Cardiologist"], ["dil mein", "Cardiologist"], ["seena", "Cardiologist"],
  ["heart", "Cardiologist"], ["bp", "Cardiologist"],
  ["back pain", "Orthopedic"], ["joint pain", "Orthopedic"], ["jodon", "Orthopedic"],
  ["fracture", "Orthopedic"], ["haddi", "Orthopedic"], ["kamar", "Orthopedic"], ["ghutna", "Orthopedic"],
  ["joint", "Orthopedic"], ["bone", "Orthopedic"], ["knee", "Orthopedic"],
  ["vaccination", "Pediatrician"], ["bachcha", "Pediatrician"], ["bacha", "Pediatrician"],
  ["child", "Pediatrician"], ["baby", "Pediatrician"],
  ["eczema", "Dermatologist"], ["psoriasis", "Dermatologist"], ["pimple", "Dermatologist"],
  ["itching", "Dermatologist"], ["kharish", "Dermatologist"], ["khujli", "Dermatologist"],
  ["chamdi", "Dermatologist"], ["acne", "Dermatologist"], ["rash", "Dermatologist"], ["skin", "Dermatologist"],
  ["aankhon", "Ophthalmologist"], ["aankh", "Ophthalmologist"], ["vision", "Ophthalmologist"],
  ["specs", "Ophthalmologist"], ["eye", "Ophthalmologist"],
  ["toothache", "Dentist"], ["daant", "Dentist"], ["dental", "Dentist"], ["tooth", "Dentist"], ["teeth", "Dentist"],
  ["depression", "Psychiatrist"], ["ghabrahad", "Psychiatrist"], ["anxiety", "Psychiatrist"],
  ["insomnia", "Psychiatrist"], ["neend", "Psychiatrist"], ["mental", "Psychiatrist"], ["stress", "Psychiatrist"],
  ["sleep", "Psychiatrist"], ["mind", "Psychiatrist"],
  ["kidney stone", "Urologist"], ["peshab", "Urologist"], ["pathri", "Urologist"], ["kidney", "Urologist"],
  ["urine", "Urologist"], ["stone", "Urologist"],
  ["diabetic", "Diabetologist"], ["diabetes", "Diabetologist"], ["thyroid", "Diabetologist"], ["sugar", "Diabetologist"],
  ["sar dard", "Neurologist"], ["sir dard", "Neurologist"], ["migraine", "Neurologist"], ["headache", "Neurologist"],
  ["tonsil", "ENT Specialist"], ["sinus", "ENT Specialist"], ["naak", "ENT Specialist"], ["kaan", "ENT Specialist"],
  ["gala", "ENT Specialist"], ["throat", "ENT Specialist"], ["ear", "ENT Specialist"],
  ["bukhar", "General Physician"], ["khansi", "General Physician"], ["stomach", "General Physician"],
  ["gastric", "General Physician"], ["acidity", "General Physician"], ["vomit", "General Physician"],
  ["nausea", "General Physician"], ["diarrhea", "General Physician"], ["fever", "General Physician"],
  ["cough", "General Physician"], ["cold", "General Physician"], ["flu", "General Physician"],
  ["pet dard", "General Physician"],
];

// Sorted by phrase length (desc) for first-match priority on longer phrases.
export const SYMPTOM_TO_SPECIALTY_SORTED: Array<[string, string]> = [...SYMPTOM_TO_SPECIALTY].sort(
  (a, b) => b[0].length - a[0].length
);

export const TYPO_MAP: Array<[RegExp, string]> = [
  [/\breleated\b/gi, "related"], [/\breleted\b/gi, "related"],
  [/\bproblam\b/gi, "problem"], [/\bprobam\b/gi, "problem"],
  [/\bdocter\b/gi, "doctor"], [/\bdokter\b/gi, "doctor"], [/\bdoctore\b/gi, "doctor"],
  [/\bspecialsit\b/gi, "specialist"], [/\bspecilaist\b/gi, "specialist"],
  [/\bappoinment\b/gi, "appointment"], [/\bappointement\b/gi, "appointment"],
  [/\bconsultaion\b/gi, "consultation"],
  [/\bcordio\b/gi, "cardio"], [/\bcordiology\b/gi, "cardiology"], [/\bcardia\b/gi, "cardiac"],
  [/\bcardilogist\b/gi, "cardiologist"], [/\bcardiologst\b/gi, "cardiologist"],
  [/\bcardioligist\b/gi, "cardiologist"], [/\bcardiolist\b/gi, "cardiologist"],
  [/\bcardiologsit\b/gi, "cardiologist"], [/\bcardiac\s*arest\b/gi, "cardiac arrest"],
  [/\bcardiac\s*arret\b/gi, "cardiac arrest"],
  [/\bginecologist\b/gi, "gynecologist"], [/\bgynocoligist\b/gi, "gynecologist"],
  [/\bgyncologist\b/gi, "gynecologist"], [/\bgynoecologist\b/gi, "gynecologist"],
  [/\bgynocologist\b/gi, "gynecologist"], [/\bginecolog\w*\b/gi, "gynecologist"],
  [/\bgynaec\b/gi, "gynecologist"], [/\bgynec\b/gi, "gynecologist"],
  [/\bnuero\b/gi, "neuro"], [/\bnuro\b/gi, "neuro"], [/\bneurolog\b/gi, "neurologist"],
  [/\bneurlogist\b/gi, "neurologist"], [/\bneuorlogist\b/gi, "neurologist"], [/\bneuologist\b/gi, "neurologist"],
  [/\borthopadic\b/gi, "orthopedic"], [/\borthopaedic\b/gi, "orthopedic"], [/\borthopaedics\b/gi, "orthopedic"],
  [/\borthoped\b/gi, "orthopedic"], [/\borthopedist\b/gi, "orthopedic doctor"],
  [/\bdermatolog\b/gi, "dermatologist"], [/\bdermtologist\b/gi, "dermatologist"],
  [/\bdermatoligist\b/gi, "dermatologist"], [/\bdermatologst\b/gi, "dermatologist"],
  [/\bopthalmolog\w*\b/gi, "ophthalmologist"], [/\bophtalmolog\w*\b/gi, "ophthalmologist"],
  [/\bopthomologist\b/gi, "ophthalmologist"], [/\bophtamologist\b/gi, "ophthalmologist"],
  [/\bpediatric\b/gi, "pediatrician"], [/\bpaediatric\b/gi, "pediatrician"],
  [/\bpeditrician\b/gi, "pediatrician"], [/\bpediatrist\b/gi, "pediatrician"], [/\bpaeditirician\b/gi, "pediatrician"],
  [/\bpsychiatri\b/gi, "psychiatrist"], [/\bpsychiartist\b/gi, "psychiatrist"],
  [/\bpsychaitrist\b/gi, "psychiatrist"], [/\bphsychiatrist\b/gi, "psychiatrist"],
  [/\bdiabetis\b/gi, "diabetes"], [/\bdibetes\b/gi, "diabetes"], [/\bdibetis\b/gi, "diabetes"],
  [/\bdiabetse\b/gi, "diabetes"], [/\bdiabetologst\b/gi, "diabetologist"],
  [/\bent specialist\b/gi, "ENT specialist"],
  [/\bstomatch\b/gi, "stomach"], [/\bstomch\b/gi, "stomach"], [/\bstomech\b/gi, "stomach"], [/\bstomak\b/gi, "stomach"],
  [/\bphsyio\b/gi, "physiotherapy"], [/\bfisio\b/gi, "physiotherapy"], [/\bphysio\b/gi, "physiotherapy"],
  [/\bphysiotheraphy\b/gi, "physiotherapy"],
  [/\burologst\b/gi, "urologist"],
  [/\bdentst\b/gi, "dentist"], [/\bdentiest\b/gi, "dentist"],
];

export const MEDICAL_VOCAB: string[] = [
  "cardiologist", "cardiology", "cardiac", "cardio",
  "gynecologist", "gynecology", "gynae",
  "neurologist", "neurology", "neuro",
  "orthopedic", "orthopedics",
  "dermatologist", "dermatology",
  "ophthalmologist", "ophthalmology",
  "pediatrician", "pediatrics",
  "psychiatrist", "psychiatry",
  "diabetologist", "diabetes", "diabetic",
  "urologist", "urology",
  "dentist", "dental",
  "physiotherapy", "physiotherapist",
  "gastroenterologist", "gastroenterology",
  "pulmonologist", "pulmonology",
  "endocrinologist", "endocrinology",
  "rheumatologist", "rheumatology",
  "nephrologist", "nephrology",
  "oncologist", "oncology",
  "anesthesiologist", "surgeon", "surgery",
  "physician", "doctor", "specialist",
  "appointment", "consultation", "treatment",
  "hospital", "clinic", "pharmacy",
  "prescription", "medicine", "medication",
  "symptom", "diagnosis", "emergency",
  "fever", "headache", "cough", "diabetes",
  "stomach", "kidney", "thyroid", "vaccination",
  // Broadened so single-word typos in common complaints self-correct before
  // ever reaching the phrase matcher.
  "ambulance", "injection", "tablet", "capsule", "syrup", "antibiotic",
  "infection", "allergy", "allergic", "asthma", "migraine", "arthritis",
  "pressure", "cholesterol", "pregnant", "pregnancy", "periods",
  "vomiting", "nausea", "diarrhea", "diarrhoea", "constipation", "acidity",
  "breathing", "breathless", "swelling", "bleeding", "burning", "itching",
  "dizziness", "weakness", "fatigue", "insomnia", "anxiety", "depression",
  "toothache", "backache", "stomachache", "earache", "sorethroat",
  "dengue", "malaria", "typhoid", "jaundice", "tuberculosis", "pneumonia",
  "appendicitis", "gastritis", "ulcer", "fracture", "sprain", "wound",
  "seizure", "unconscious", "fainting", "nosebleed", "sunstroke",
  "paracetamol", "ibuprofen", "antacid", "vitamin", "supplement",
];

export const FUZZY_STOP_WORDS = new Set<string>([
  "doctar", "doctar.in",
  "i", "me", "my", "am", "is", "are", "was", "be", "been", "being",
  "have", "has", "had", "do", "does", "did", "will", "would", "could",
  "should", "may", "might", "shall", "can", "a", "an", "the", "and",
  "but", "or", "for", "so", "in", "on", "at", "to", "of", "by", "from",
  "up", "with", "about", "no", "not", "only", "same", "than", "very",
  "just", "it", "its", "this", "that", "these", "those", "he", "she",
  "they", "we", "you", "get", "find", "show", "book", "near", "here",
  "there", "what", "which", "who", "when", "where", "why", "how",
  "hi", "hello", "please", "help", "want", "like", "know", "think",
  "mujhe", "mera", "mere", "meri", "hai", "hain", "ho", "rha", "rhi",
  "ke", "ka", "ki", "se", "ko", "aur", "ya", "nahi", "kya", "hoon",
]);
