/**
 * Offline known-medicine database for label analysis (ported from medicine_label.py).
 * Keys are lowercase brand/generic names that appear on Indian labels; the lookup
 * checks if any key appears anywhere in the OCR text.
 */
export interface LabelInfo {
  uses: string[];
  dosage: string;
  side_effects: string[];
  warnings: string[];
  storage: string;
  generic_name?: string;
  manufacturer?: string;
  prescription_required?: boolean;
}

export const KNOWN_MEDICINES_LABEL: Record<string, LabelInfo> = {
  paracetamol: {
    uses: ["Fever / बुखार", "Mild to moderate pain / दर्द", "Headache / सिरदर्द"],
    dosage: "Adults: 500–1000mg every 4–6 hours. Max 4g/day. Children: as per weight",
    side_effects: ["Nausea (rare)", "Liver damage if overdosed"],
    warnings: ["Do not exceed recommended dose", "Avoid alcohol", "Paracetamol overdose may be injurious to liver"],
    storage: "Store below 30°C, protect from light and moisture",
  },
  calpol: {
    uses: ["Fever / बुखार", "Mild to moderate pain / दर्द", "Headache / सिरदर्द"],
    dosage: "Calpol 650: 1 tablet every 4–6 hours as directed by physician",
    side_effects: ["Nausea (rare)", "Liver damage if overdosed"],
    warnings: ["Do not exceed recommended dose", "Avoid alcohol", "Paracetamol overdose may be injurious to liver"],
    storage: "Store at temperature not exceeding 30°C, protect from light and moisture",
    generic_name: "Paracetamol IP 650 mg",
    manufacturer: "GlaxoSmithKline Pharmaceuticals Limited",
  },
  dolo: {
    uses: ["Fever / बुखार", "Pain / दर्द", "Headache / सिरदर्द"],
    dosage: "1 tablet (650mg) every 4–6 hours as needed. Max 4 tablets/day",
    side_effects: ["Nausea (rare)", "Liver damage if overdosed"],
    warnings: ["Do not exceed recommended dose", "Avoid alcohol"],
    storage: "Store below 30°C",
    generic_name: "Paracetamol IP 650 mg",
    manufacturer: "Micro Labs Limited",
  },
  crocin: {
    uses: ["Fever / बुखार", "Pain / दर्द", "Cold & flu symptoms"],
    dosage: "500mg every 4–6 hours. Max 4g/day",
    side_effects: ["Nausea (rare)", "Liver damage if overdosed"],
    warnings: ["Do not exceed recommended dose", "Avoid alcohol"],
    storage: "Store below 30°C",
    generic_name: "Paracetamol",
    manufacturer: "GlaxoSmithKline Pharmaceuticals",
  },
  ibuprofen: {
    uses: ["Pain relief / दर्द", "Fever / बुखार", "Inflammation / सूजन", "Arthritis"],
    dosage: "Adults: 400mg every 6–8 hours after food. Max 1200mg/day",
    side_effects: ["Stomach upset", "Nausea", "Dizziness", "Gastric bleeding (rare)"],
    warnings: ["Always take with food or milk", "Avoid in kidney/liver disease", "Not for children under 6 months", "Avoid in last trimester of pregnancy"],
    storage: "Store below 25°C",
  },
  brufen: {
    uses: ["Pain relief / दर्द", "Fever / बुखार", "Arthritis", "Inflammation / सूजन"],
    dosage: "400mg 3 times daily after food",
    side_effects: ["Stomach upset", "Nausea", "Gastric ulcer (long use)"],
    warnings: ["Take with food", "Avoid in kidney disease", "Avoid if peptic ulcer"],
    storage: "Store below 30°C",
    generic_name: "Ibuprofen IP 400 mg",
  },
  combiflam: {
    uses: ["Pain & fever / दर्द और बुखार", "Musculoskeletal pain", "Headache", "Toothache"],
    dosage: "1 tablet 3 times daily after food",
    side_effects: ["Stomach upset", "Nausea", "Gastric irritation"],
    warnings: ["Take with food", "Not for long-term use without doctor's advice", "Avoid in kidney/liver disease"],
    storage: "Store below 25°C",
    generic_name: "Ibuprofen 400mg + Paracetamol 325mg",
    manufacturer: "Sanofi India Limited",
  },
  diclofenac: {
    uses: ["Pain / दर्द", "Arthritis", "Inflammation / सूजन", "Back pain", "Muscle pain"],
    dosage: "50mg 2–3 times daily after food, or as prescribed",
    side_effects: ["Stomach upset", "Nausea", "Gastric irritation", "Headache"],
    warnings: ["Take with food", "Avoid in heart disease", "Not for long-term use"],
    storage: "Store below 30°C",
  },
  voveran: {
    uses: ["Pain / दर्द", "Arthritis", "Inflammation", "Musculoskeletal disorders"],
    dosage: "50mg 2–3 times daily after food",
    side_effects: ["Stomach upset", "Nausea", "Headache"],
    warnings: ["Take with food", "Avoid in kidney/liver disease", "Not for long-term use"],
    storage: "Store below 25°C",
    generic_name: "Diclofenac Sodium 50 mg",
  },
  aceclofenac: {
    uses: ["Pain / दर्द", "Arthritis", "Joint pain", "Inflammation"],
    dosage: "100mg twice daily after food",
    side_effects: ["Stomach upset", "Nausea", "Diarrhea"],
    warnings: ["Take with food", "Avoid in kidney/liver disease"],
    storage: "Store below 30°C",
  },
  amoxicillin: {
    uses: ["Bacterial infections / बैक्टीरियल संक्रमण", "Ear/throat/chest infections", "UTI", "Dental infections"],
    dosage: "250–500mg three times daily for 5–10 days as prescribed",
    side_effects: ["Diarrhea", "Nausea", "Skin rash", "Allergic reaction"],
    warnings: ["Complete the full course", "Tell doctor if allergic to penicillin", "Do not stop early"],
    storage: "Store below 25°C",
  },
  amoxyclav: {
    uses: ["Bacterial infections", "Respiratory infections", "UTI", "Skin infections"],
    dosage: "625mg (500+125) twice daily after food for 5–7 days",
    side_effects: ["Diarrhea", "Nausea", "Stomach upset", "Rash"],
    warnings: ["Complete full course", "Take after food to reduce stomach upset", "Tell doctor about penicillin allergy"],
    storage: "Store below 25°C",
    generic_name: "Amoxicillin + Clavulanate Potassium",
  },
  augmentin: {
    uses: ["Bacterial infections", "Respiratory / ENT infections", "UTI", "Skin infections"],
    dosage: "625mg twice daily after food",
    side_effects: ["Diarrhea", "Nausea", "Vomiting", "Rash"],
    warnings: ["Complete full course", "Take after food", "Tell doctor if allergic to penicillin"],
    storage: "Store below 25°C",
    generic_name: "Amoxicillin 500mg + Clavulanic Acid 125mg",
    manufacturer: "GlaxoSmithKline Pharmaceuticals",
  },
  azithromycin: {
    uses: ["Bacterial infections", "Respiratory tract infections", "Skin & soft tissue infections", "STIs"],
    dosage: "500mg once daily for 3 days, or 250mg daily for 5 days as prescribed",
    side_effects: ["Nausea", "Diarrhea", "Abdominal pain", "Vomiting"],
    warnings: ["Complete the full course", "Tell doctor about heart conditions (QT prolongation)", "Avoid antacids within 2 hours"],
    storage: "Store below 30°C",
  },
  azee: {
    uses: ["Bacterial infections", "Respiratory infections", "Skin infections"],
    dosage: "500mg once daily for 3 days as prescribed",
    side_effects: ["Nausea", "Diarrhea", "Abdominal pain"],
    warnings: ["Complete full course", "Tell doctor about heart conditions"],
    storage: "Store below 30°C",
    generic_name: "Azithromycin 500 mg",
  },
  ciprofloxacin: {
    uses: ["UTI / मूत्र मार्ग संक्रमण", "Respiratory infections", "Gastroenteritis", "Typhoid"],
    dosage: "250–500mg twice daily for 3–7 days as prescribed",
    side_effects: ["Nausea", "Diarrhea", "Headache", "Tendon damage (rare)"],
    warnings: ["Avoid in children/adolescents", "Avoid excessive sunlight", "Do not take with antacids"],
    storage: "Store below 25°C, protect from light",
  },
  metronidazole: {
    uses: ["Bacterial & parasitic infections", "Amoebic dysentery", "Giardiasis", "Anaerobic infections"],
    dosage: "400mg three times daily for 5–7 days as prescribed",
    side_effects: ["Nausea", "Metallic taste", "Dizziness", "Headache"],
    warnings: ["Strictly avoid alcohol during treatment", "Complete full course"],
    storage: "Store below 30°C, protect from light",
  },
  flagyl: {
    uses: ["Bacterial infections", "Amoebic dysentery", "Giardiasis"],
    dosage: "400mg three times daily for 5–7 days",
    side_effects: ["Nausea", "Metallic taste", "Dizziness"],
    warnings: ["Do NOT drink alcohol during treatment", "Complete full course"],
    storage: "Store below 30°C, protect from light",
    generic_name: "Metronidazole 400 mg",
  },
  doxycycline: {
    uses: ["Bacterial infections", "Acne", "Malaria prevention", "Respiratory infections"],
    dosage: "100mg once or twice daily as prescribed",
    side_effects: ["Nausea", "Photosensitivity", "Esophageal irritation"],
    warnings: ["Take with plenty of water, do not lie down for 30 min after", "Avoid sun exposure", "Not for children under 8 years"],
    storage: "Store below 30°C, protect from light and moisture",
  },
  omeprazole: {
    uses: ["Acidity / एसिडिटी", "GERD / Acid reflux", "Stomach ulcer", "Heartburn / सीने में जलन"],
    dosage: "20–40mg once daily 30 minutes before meals",
    side_effects: ["Headache", "Nausea", "Diarrhea", "Abdominal pain"],
    warnings: ["Do not crush or chew capsule", "Long-term use: consult doctor", "May mask symptoms of gastric cancer"],
    storage: "Store below 25°C",
  },
  pantoprazole: {
    uses: ["Acidity / एसिडिटी", "GERD", "Stomach ulcer", "Zollinger-Ellison syndrome"],
    dosage: "40mg once daily before breakfast",
    side_effects: ["Headache", "Diarrhea", "Nausea", "Flatulence"],
    warnings: ["Long-term use: consult doctor", "May reduce magnesium levels"],
    storage: "Store below 30°C",
  },
  pan: {
    uses: ["Acidity / एसिडिटी", "GERD", "Ulcer"],
    dosage: "40mg once daily before breakfast",
    side_effects: ["Headache", "Diarrhea", "Nausea"],
    warnings: ["Consult doctor for long-term use"],
    storage: "Store below 30°C",
    generic_name: "Pantoprazole 40 mg",
  },
  ranitidine: {
    uses: ["Acidity", "GERD", "Stomach ulcer", "Heartburn"],
    dosage: "150mg twice daily or 300mg at bedtime",
    side_effects: ["Headache", "Constipation", "Diarrhea"],
    warnings: ["Tell doctor about kidney problems"],
    storage: "Store below 25°C, protect from light",
  },
  gelusil: {
    uses: ["Acidity / एसिडिटी", "Heartburn / सीने में जलन", "Indigestion / अपच", "Flatulence"],
    dosage: "1–2 tablets or 2 tsp syrup after meals and at bedtime",
    side_effects: ["Constipation (with aluminum)", "Diarrhea (with magnesium)"],
    warnings: ["Do not take within 2 hours of other medicines", "Avoid long-term use"],
    storage: "Store below 30°C",
    generic_name: "Aluminium Hydroxide + Magnesium Hydroxide + Simethicone",
  },
  domperidone: {
    uses: ["Nausea / मतली", "Vomiting / उल्टी", "Gastroparesis", "Bloating"],
    dosage: "10mg three times daily 15–30 minutes before meals",
    side_effects: ["Headache", "Dry mouth", "Drowsiness"],
    warnings: ["Not for long-term use", "Avoid in heart disease", "Use minimum effective dose"],
    storage: "Store below 30°C",
  },
  cetirizine: {
    uses: ["Allergic rhinitis / एलर्जी", "Urticaria / पित्ती", "Itching / खुजली", "Hay fever"],
    dosage: "10mg once daily, preferably at night",
    side_effects: ["Drowsiness", "Dry mouth", "Dizziness", "Fatigue"],
    warnings: ["Avoid driving/heavy machinery", "Avoid alcohol", "Reduces with food"],
    storage: "Store below 30°C",
  },
  levocetrizine: {
    uses: ["Allergic rhinitis / एलर्जी", "Chronic urticaria / पित्ती", "Itching / खुजली"],
    dosage: "5mg once daily in the evening",
    side_effects: ["Drowsiness", "Headache", "Dry mouth"],
    warnings: ["Avoid driving", "Avoid alcohol", "Caution in kidney disease"],
    storage: "Store below 30°C",
  },
  allegra: {
    uses: ["Allergic rhinitis", "Urticaria", "Itching", "Sneezing"],
    dosage: "120mg or 180mg once daily",
    side_effects: ["Headache", "Nausea", "Drowsiness (less than older antihistamines)"],
    warnings: ["Avoid fruit juice (reduces absorption)", "Caution in kidney disease"],
    storage: "Store below 30°C",
    generic_name: "Fexofenadine",
  },
  fexofenadine: {
    uses: ["Allergic rhinitis", "Urticaria", "Itching"],
    dosage: "120mg or 180mg once daily",
    side_effects: ["Headache", "Nausea", "Drowsiness (low risk)"],
    warnings: ["Avoid fruit juices — reduce drug absorption", "Caution in kidney disease"],
    storage: "Store below 30°C",
  },
  montelukast: {
    uses: ["Allergic rhinitis / एलर्जी", "Asthma prevention", "Exercise-induced asthma"],
    dosage: "10mg once daily in the evening",
    side_effects: ["Headache", "Abdominal pain", "Mood changes (rare)"],
    warnings: ["Not for acute asthma attacks", "Mood/behavior changes: tell doctor"],
    storage: "Store below 25°C, protect from moisture and light",
  },
  benadryl: {
    uses: ["Cough & cold / खांसी और सर्दी", "Allergic symptoms", "Runny nose"],
    dosage: "10ml (2 tsp) 3–4 times daily. Children: as per age",
    side_effects: ["Drowsiness", "Dry mouth", "Dizziness"],
    warnings: ["Avoid driving", "Avoid alcohol", "Do not give to children under 2 years"],
    storage: "Store below 30°C",
    generic_name: "Diphenhydramine + Ammonium Chloride + Sodium Citrate",
  },
  alex: {
    uses: ["Cough / खांसी", "Cold", "Congestion", "Runny nose"],
    dosage: "10ml three times daily",
    side_effects: ["Drowsiness", "Dry mouth", "Dizziness"],
    warnings: ["Avoid driving", "Avoid alcohol", "Not for children under 2 years"],
    storage: "Store below 30°C",
    generic_name: "Chlorpheniramine + Dextromethorphan + Guaifenesin",
  },
  sinarest: {
    uses: ["Cold & flu / सर्दी और फ्लू", "Nasal congestion / बंद नाक", "Headache", "Sinusitis"],
    dosage: "1 tablet every 6–8 hours",
    side_effects: ["Drowsiness", "Dry mouth", "Palpitations"],
    warnings: ["Avoid driving", "Avoid alcohol", "Not for hypertension patients", "Do not take with other cold medicines"],
    storage: "Store below 30°C",
    generic_name: "Paracetamol + Phenylephrine + Chlorpheniramine",
  },
  dextromethorphan: {
    uses: ["Dry cough / सूखी खांसी"],
    dosage: "10–20mg every 4–6 hours as needed. Max 120mg/day",
    side_effects: ["Drowsiness", "Dizziness", "Nausea"],
    warnings: ["Avoid in productive cough", "Avoid alcohol", "Do not use with MAO inhibitors"],
    storage: "Store below 30°C",
  },
  salbutamol: {
    uses: ["Asthma / दमा", "COPD", "Bronchospasm", "Breathing difficulty"],
    dosage: "Inhaler: 100–200mcg (1–2 puffs) as needed. Tablet: 2–4mg 3 times daily",
    side_effects: ["Tremor / कंपन", "Palpitations", "Headache", "Muscle cramps"],
    warnings: ["Overuse can be dangerous", "Tell doctor about heart conditions", "Shake inhaler before use"],
    storage: "Store below 30°C, protect from direct sunlight",
  },
  asthalin: {
    uses: ["Asthma / दमा", "Bronchospasm", "COPD", "Breathing difficulty"],
    dosage: "1–2 puffs (100mcg each) every 4–6 hours as needed",
    side_effects: ["Tremor", "Palpitations", "Headache"],
    warnings: ["Overuse can be dangerous", "Seek emergency care if not relieved", "Shake before use"],
    storage: "Store below 30°C, protect from sunlight and frost",
    generic_name: "Salbutamol Sulphate 100 mcg/dose",
  },
  metformin: {
    uses: ["Type 2 diabetes / मधुमेह", "Blood sugar control / शुगर नियंत्रण", "PCOS"],
    dosage: "500–1000mg twice daily with meals. Start low, increase gradually",
    side_effects: ["Nausea", "Diarrhea", "Stomach upset (reduces with food)"],
    warnings: ["Take with food to reduce side effects", "Monitor blood sugar regularly", "Not for severe kidney/liver disease", "Stop before contrast procedures"],
    storage: "Store at room temperature, below 25°C",
  },
  glucophage: {
    uses: ["Type 2 diabetes / मधुमेह", "Blood sugar control"],
    dosage: "500mg twice daily with meals, increasing to 1000mg twice daily",
    side_effects: ["Nausea", "Diarrhea", "Stomach cramps"],
    warnings: ["Take with food", "Monitor kidney function", "Stop before surgery/contrast scans"],
    storage: "Store below 25°C",
    generic_name: "Metformin Hydrochloride",
  },
  glimepiride: {
    uses: ["Type 2 diabetes / मधुमेह"],
    dosage: "1–4mg once daily with breakfast",
    side_effects: ["Hypoglycemia / कम शुगर", "Weight gain", "Nausea"],
    warnings: ["Do not skip meals", "Carry sugar candy for low blood sugar", "Avoid alcohol"],
    storage: "Store below 30°C, protect from moisture",
  },
  januvia: {
    uses: ["Type 2 diabetes / मधुमेह", "Blood sugar control"],
    dosage: "100mg once daily, with or without food",
    side_effects: ["Upper respiratory infection", "Headache", "Pancreatitis (rare)"],
    warnings: ["Report severe abdominal pain", "Monitor kidney function"],
    storage: "Store below 30°C",
    generic_name: "Sitagliptin 100 mg",
  },
  amlodipine: {
    uses: ["High blood pressure / उच्च रक्तचाप", "Angina", "Heart disease prevention"],
    dosage: "5–10mg once daily",
    side_effects: ["Ankle swelling", "Flushing", "Headache", "Dizziness"],
    warnings: ["Do not stop suddenly without doctor advice", "Monitor blood pressure regularly"],
    storage: "Store below 30°C",
  },
  telmisartan: {
    uses: ["High blood pressure / उच्च रक्तचाप", "Heart failure", "Kidney protection in diabetes"],
    dosage: "40–80mg once daily",
    side_effects: ["Dizziness", "Back pain", "Diarrhea"],
    warnings: ["Avoid in pregnancy", "Monitor potassium levels", "Do not stop suddenly"],
    storage: "Store below 30°C, protect from moisture",
  },
  losartan: {
    uses: ["High blood pressure / उच्च रक्तचाप", "Heart failure", "Kidney protection"],
    dosage: "50–100mg once daily",
    side_effects: ["Dizziness", "Fatigue", "High potassium"],
    warnings: ["Avoid in pregnancy", "Monitor kidney function and potassium", "Do not stop suddenly"],
    storage: "Store below 30°C",
  },
  atenolol: {
    uses: ["High blood pressure / उच्च रक्तचाप", "Angina", "Heart rate control"],
    dosage: "25–100mg once daily",
    side_effects: ["Fatigue", "Cold extremities", "Bradycardia (slow heart rate)", "Depression"],
    warnings: ["Do not stop suddenly — taper gradually", "May mask hypoglycemia symptoms", "Avoid in asthma"],
    storage: "Store below 25°C, protect from moisture and light",
  },
  metoprolol: {
    uses: ["High blood pressure", "Heart failure", "Angina", "Arrhythmia"],
    dosage: "25–100mg once or twice daily",
    side_effects: ["Fatigue", "Dizziness", "Bradycardia", "Cold hands/feet"],
    warnings: ["Do not stop suddenly", "Avoid in asthma/COPD", "Monitor heart rate"],
    storage: "Store below 30°C",
  },
  ecosprin: {
    uses: ["Blood thinner / खून पतला", "Heart attack prevention", "Stroke prevention", "Platelet aggregation"],
    dosage: "75–150mg once daily, usually at night after food",
    side_effects: ["Stomach upset", "Gastric bleeding (long term)", "Nausea"],
    warnings: ["Take with food", "Avoid in bleeding disorders", "Tell doctor before any surgery", "Avoid high doses"],
    storage: "Store below 25°C, protect from moisture",
    generic_name: "Aspirin / Acetylsalicylic Acid",
  },
  aspirin: {
    uses: ["Blood thinner / खून पतला", "Heart attack & stroke prevention", "Pain relief", "Fever"],
    dosage: "Cardiac: 75–150mg once daily. Pain: 300–600mg every 4–6 hours",
    side_effects: ["Stomach upset", "Gastric bleeding", "Tinnitus (high doses)"],
    warnings: ["Avoid in children under 12 (Reye's syndrome)", "Take with food", "Tell doctor before surgery"],
    storage: "Store below 25°C, protect from moisture",
  },
  atorvastatin: {
    uses: ["High cholesterol / उच्च कोलेस्ट्रॉल", "Heart disease prevention", "Triglycerides"],
    dosage: "10–80mg once daily at night",
    side_effects: ["Muscle pain / myalgia", "Weakness", "Liver enzyme increase", "Headache"],
    warnings: ["Report unexplained muscle pain or weakness immediately", "Avoid grapefruit juice", "Regular liver function tests for long-term use"],
    storage: "Store below 30°C",
  },
  rosuvastatin: {
    uses: ["High cholesterol", "Heart disease prevention", "Triglycerides"],
    dosage: "5–40mg once daily",
    side_effects: ["Muscle pain", "Headache", "Nausea", "Abdominal pain"],
    warnings: ["Report muscle pain immediately", "Avoid excessive alcohol", "Regular monitoring"],
    storage: "Store below 30°C, protect from moisture",
  },
  levothyroxine: {
    uses: ["Hypothyroidism / थायरॉयड", "Thyroid hormone replacement"],
    dosage: "25–200mcg once daily, 30–60 minutes before breakfast on empty stomach",
    side_effects: ["Palpitations", "Weight loss", "Tremors (if overdosed)", "Insomnia"],
    warnings: ["Take on empty stomach, 30 min before breakfast", "Do not switch brands without doctor advice", "Regular TSH monitoring"],
    storage: "Store below 25°C, protect from light and moisture",
  },
  thyronorm: {
    uses: ["Hypothyroidism / थायरॉयड", "Thyroid hormone replacement"],
    dosage: "As prescribed. Take on empty stomach 30–60 min before breakfast",
    side_effects: ["Palpitations", "Sweating", "Weight loss (if over-dosed)"],
    warnings: ["Empty stomach — critical for absorption", "Regular TSH tests", "Inform doctor of all other medicines"],
    storage: "Store below 25°C, protect from light",
    generic_name: "Levothyroxine Sodium",
  },
  eltroxin: {
    uses: ["Hypothyroidism / थायरॉयड"],
    dosage: "As prescribed by doctor. Empty stomach, 30 min before breakfast",
    side_effects: ["Palpitations", "Tremors if over-dosed"],
    warnings: ["Take on empty stomach", "Regular thyroid tests", "Do not stop without doctor advice"],
    storage: "Store below 25°C, protect from light and moisture",
    generic_name: "Levothyroxine Sodium",
  },
  "vitamin d": {
    uses: ["Vitamin D deficiency", "Bone health", "Immune support", "Calcium absorption"],
    dosage: "As prescribed. Common: 60,000 IU weekly or 1000–2000 IU daily",
    side_effects: ["Nausea (if overdosed)", "Weakness", "Frequent urination"],
    warnings: ["Do not exceed prescribed dose", "Toxicity possible with very high doses"],
    storage: "Store below 30°C, protect from light",
  },
  shelcal: {
    uses: ["Calcium & Vitamin D deficiency", "Bone health", "Osteoporosis prevention"],
    dosage: "1 tablet twice daily after food",
    side_effects: ["Constipation", "Bloating", "Nausea"],
    warnings: ["Take after food", "Drink plenty of water", "Avoid excess dose"],
    storage: "Store below 30°C, protect from moisture",
    generic_name: "Calcium Carbonate 500mg + Vitamin D3 250 IU",
  },
  becosules: {
    uses: ["Vitamin B complex deficiency", "General wellness", "Mouth ulcers", "Fatigue"],
    dosage: "1 capsule once daily after food",
    side_effects: ["Urine discoloration (yellow — normal)", "Nausea (rare)"],
    warnings: ["Urine may turn bright yellow — this is normal and harmless"],
    storage: "Store below 30°C, protect from moisture",
    generic_name: "Vitamin B Complex with Vitamin C",
    manufacturer: "Pfizer Limited",
  },
  neurobion: {
    uses: ["Vitamin B deficiency", "Nerve pain / neuropathy", "Numbness / tingling", "Weakness"],
    dosage: "1 tablet once daily, or as prescribed",
    side_effects: ["Nausea (rare)", "Allergic reaction (rare)"],
    warnings: ["Do not exceed recommended dose"],
    storage: "Store below 30°C, protect from light and moisture",
    generic_name: "Vitamin B1 + B6 + B12",
  },
  iron: {
    uses: ["Iron deficiency anaemia / खून की कमी", "During pregnancy", "Fatigue due to low iron"],
    dosage: "1 tablet once or twice daily",
    side_effects: ["Constipation", "Black stools (normal)", "Stomach upset", "Nausea"],
    warnings: ["Black/dark stools are normal", "Take with vitamin C for better absorption", "Keep away from children"],
    storage: "Store below 30°C, protect from light and moisture",
  },
  "folic acid": {
    uses: ["Folic acid deficiency", "During pregnancy (neural tube defect prevention)", "Anaemia"],
    dosage: "Pregnancy: 400mcg–5mg daily. Deficiency: 5mg daily",
    side_effects: ["Nausea (rare)", "Bloating (rare)"],
    warnings: ["Crucial to start before and during early pregnancy"],
    storage: "Store below 30°C, protect from light",
  },
  betadine: {
    uses: ["Wound disinfection / घाव साफ करना", "Skin infection prevention", "Surgical scrub"],
    dosage: "Apply directly to wound or affected area. Dilute 1:10 for sensitive areas",
    side_effects: ["Skin irritation", "Staining (brown)", "Allergic reaction (rare)"],
    warnings: ["Do not swallow", "Avoid on large wounds for long periods", "Not for thyroid patients in large amounts"],
    storage: "Store below 30°C, protect from light",
    generic_name: "Povidone Iodine",
  },
  soframycin: {
    uses: ["Bacterial skin infections", "Cuts & wounds / कटे-जले", "Burns", "Infected skin"],
    dosage: "Apply thin layer on affected area 2–3 times daily",
    side_effects: ["Skin irritation", "Allergic reaction (rare)"],
    warnings: ["External use only", "Avoid contact with eyes"],
    storage: "Store below 25°C",
    generic_name: "Framycetin Sulphate",
  },
  calamine: {
    uses: ["Itching / खुजली", "Sunburn", "Insect bites", "Prickly heat / घमौरियां", "Mild rashes"],
    dosage: "Apply to affected area 2–3 times daily",
    side_effects: ["Skin dryness (with excessive use)"],
    warnings: ["External use only", "Avoid eyes and mucous membranes"],
    storage: "Store below 30°C",
    generic_name: "Calamine + Zinc Oxide",
  },
  alprazolam: {
    uses: ["Anxiety / चिंता", "Panic disorder", "Insomnia / नींद न आना"],
    dosage: "0.25–0.5mg 2–3 times daily. Max 4mg/day",
    side_effects: ["Drowsiness", "Dizziness", "Dependency if long-term use"],
    warnings: ["Schedule H — prescription required", "Do NOT stop suddenly — may cause withdrawal", "Avoid alcohol", "May cause dependence with long-term use"],
    storage: "Store below 25°C, protect from light",
    prescription_required: true,
  },
  clonazepam: {
    uses: ["Epilepsy / मिर्गी", "Panic disorder", "Anxiety"],
    dosage: "0.5mg twice daily initially, adjusted by doctor",
    side_effects: ["Drowsiness", "Dizziness", "Memory problems", "Dependency"],
    warnings: ["Schedule H — prescription required", "Do NOT stop suddenly — seizure risk", "Avoid alcohol and driving"],
    storage: "Store below 25°C, protect from light",
    prescription_required: true,
  },
  volini: {
    uses: ["Muscle pain / मांसपेशी दर्द", "Joint pain / जोड़ों का दर्द", "Sprain / मोच", "Back pain"],
    dosage: "Apply gel/spray to affected area 2–3 times daily. Massage gently",
    side_effects: ["Skin irritation", "Burning sensation", "Redness"],
    warnings: ["External use only", "Avoid eyes and open wounds", "Do not use on broken skin"],
    storage: "Store below 30°C",
    generic_name: "Diclofenac Diethylamine + Methyl Salicylate + Menthol",
  },
  moov: {
    uses: ["Muscle pain / मांसपेशी दर्द", "Joint pain", "Backache", "Sprain"],
    dosage: "Apply to affected area 2–3 times daily",
    side_effects: ["Skin irritation", "Burning sensation"],
    warnings: ["External use only", "Avoid eyes and mucous membranes"],
    storage: "Store below 30°C",
    generic_name: "Diclofenac Diethylamine + Linseed Oil + Methyl Salicylate + Menthol",
  },
  ors: {
    uses: ["Dehydration / निर्जलीकरण", "Diarrhea / दस्त", "Vomiting", "Heat exhaustion"],
    dosage: "Dissolve 1 sachet in 1 litre of clean water. Sip frequently",
    side_effects: ["Nausea (rare)", "Hypernatremia if over-concentrated"],
    warnings: ["Use correct water amount — do not concentrate", "Do not boil after mixing", "Use within 24 hours"],
    storage: "Store in cool, dry place",
    generic_name: "Oral Rehydration Salts — WHO formula",
  },
  electral: {
    uses: ["Dehydration / निर्जलीकरण", "Diarrhea", "Vomiting", "Excessive sweating"],
    dosage: "Dissolve 1 sachet in 1 litre water. Drink as required",
    side_effects: ["Bloating (rare)"],
    warnings: ["Use correct concentration", "Discard unused solution after 24 hours"],
    storage: "Store in cool, dry place",
    generic_name: "Sodium Chloride + Potassium Chloride + Sodium Citrate + Glucose",
  },
};
